### ISSUE TITLE
target mapped event before merging update

### ISSUE THREAD

**Issue by vitalz** [nhl/link-move#114]
For now, this 

`com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateMerger.merge(ObjectContext, Map<Object, Map<String, Object>>, List<T>)`

 method does two actions per one step - it maps source to target and **also** updates the last one, i.e.:

```
 Object key = mapper.keyForTarget(t);
 Map<String, Object> src = localMappedSources.remove(key);

```

```
// skip phantom updates...
if (update(context, src, t)) {
        result.add(new CreateOrUpdateTuple<>(src, t, false));
}
```

That's done per one step, i.e. only one event fired which is called _@AfterTargetsMerged_. But I wonder if we might split this 'step' to two events, like: 

> @AfterTargetsMergedMapped
> @AfterTargetsMergedUpdated

@andrus  Does it makes sense to LinkMove users?

**Comment by andrus** [comment]
@vitalz : we haven't had any requests to split it, but logically it does make sense. 

As long as we don't check for phantom updates twice after such refactoring (which can be done by adding ```TargetPropertyWriter.willWrite(..)``` method or something along these lines), I'd be +1 on this change.

**Comment by atomashpolskiy** [comment]
@andrus , by phantom updates you mean CreateOrUpdateTuples that won't be included in the final commit because target values are already up-to-date? I'm asking this because, if I remember correctly, @vitalz 's idea was to get the list of CreateOrUpdateTuples with **not yet updated** targets (not sure how that should work for new targets -- is it supposed to be null or missing?). If is_updated/is_created flag is also expected to be set correctly, then I can't see how we might avoid checking for updates twice (because something might have changed in the context between two stages).

**Comment by andrus** [comment]
> by phantom updates you mean CreateOrUpdateTuples that won't be included in the final commit because target values are already up-to-date?

Yes

> If is_updated/is_created flag is also expected to be set correctly, then I can't see how we might avoid checking for updates twice (because something might have changed in the context between two stages).

I only took a quick look, but I think we can do that. We replace "TargetPropertyWriter.write" call with new method "TargetPropertyWriter.willWrite" call on the first pass. I think this will allow us to to sort out real vs phantom updates and new vs updated objects.  Then we can reimplement "write" to avoid any further checks for phantom updates. And use "write" in the second stage.
